[package]
name = "gitlab_untar"
version = "0.1.0"
authors = ["Éric BURGHARD <eric.burghard@solarsis.co.ao>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gitlab = "=0.1200.2"
clap = { path = "../clap" }